### ISSUE TITLE
Errror 404 with wget ( not related to bash version)

### ISSUE THREAD

**Issue by ssedoud** [igrigorik/gharchive.org#201] opened 2018-10-28 04:52 UTC
Hi,

I am having an issue downloading the archive files.

I think this is not related to my bash version( i have the 4.4.19(1)-release version)
`
$ wget "http://data.gharchive.org/2015-01-\{01..31\}.json.gz"   
--2018-10-28 05:42:42--  http://data.gharchive.org/2015-01-%5C%7B01..31%5C%7D.json.gz
Resolving data.gharchive.org (data.gharchive.org)... 104.27.165.156, 104.27.164.156, 2606:4700:30::681b:a59c, ...
Connecting to data.gharchive.org (data.gharchive.org)|104.27.165.156|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-28 05:42:43 ERROR 404: Not Found.
`

**Comment by kimyoungjin06** [comment] 2019-01-22 06:10
I am having a similar problem.

1) Connection timed out (high probabibly)

2019-01-22 05:58:46--  http://data.gharchive.org/2018-05-07-6.json.gz
Resolving data.gharchive.org (data.gharchive.org)... 104.27.165.156, 104.27.164.156, 2606:4700:30::681b:a59c, ...
Connecting to data.gharchive.org (data.gharchive.org)|104.27.165.156|:80... failed: Connection timed out.
Connecting to data.gharchive.org (data.gharchive.org)|104.27.164.156|:80... failed: Connection timed out.
Connecting to data.gharchive.org (data.gharchive.org)|2606:4700:30::681b:a59c|:80... failed: Cannot assign requested address.
Connecting to data.gharchive.org (data.gharchive.org)|2606:4700:30::681b:a49c|:80... failed: Cannot assign requested address.
Retrying.

2) same problem from @ssedoud 


Is it some traffic problem or other issue?

**Comment by igrigorik** [comment] 2019-02-13 07:17
Can't reproduce this.. Perhaps a transient network error? Closing, but feel free to reopen if you're still seeing this error.

**Closed by igrigorik** 2019-02-13 07:17 UTC
